# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import triton
import triton.language as tl
        import torch


        lut = torch.empty(_NA * _NB, dtype=torch.int16, device=device)
        _lut_build_kernel[(triton.cdiv(_NA * _NB, _BLOCK),)](
            lut, NA=_NA, NB=_NB, ITERS=16, BLOCK=_BLOCK
        )
        _TABLES[key] = lut
    return lut


def gcd_(A, B):
    n = A.numel()
    grid = (triton.cdiv(n, _BLOCK),)
    _gcd_k2_kernel[grid](A, B, _get_lut(A.device), n, NA=_NA, NB=_NB, BLOCK=_BLOCK)
    return A
